/*
 * Stoatworks Labs - About window data for Toner.
 *
 * PROVISIONAL hand copy, adapted from a sibling on 2026-09-24. The real
 * file is GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json once the project is registered there; the next
 * sync overwrites this one. `guide` is empty because no user guide exists
 * yet, so no button is drawn for it (StoatworksAboutLinks.h counts the
 * buttons from what is present).
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Toner";
    inline constexpr auto slug = "toner";
    inline constexpr auto hook = "A photocopier, and a copy of a copy of a copy, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/toner/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/toner";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
